name: PR Auto Release

on:
    pull_request:
      types: [closed]
      branches:
        - '**'
    workflow_dispatch:
jobs:
  auto-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Check runner_tools
          uses: actions/checkout@v4
          with:
            repository: StarCitizenToolBox/runner_tools
            path: runner_tools
            ref: dev
          
        - name: Set up Rust
          uses: dtolnay/rust-toolchain@stable
  
        - name: Rust Cache
          uses: Swatinem/rust-cache@v2
          with:
            workspaces: "runner_tools/localization"
            cache-all-crates: true
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            shared-key: |
              ${{ runner.os }}-cargo-

        - name: Auto Release
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
          run: cargo run --release --manifest-path ./runner_tools/localization/Cargo.toml -- -m auto_release --gh-repo "${{ github.repository }}" --gh-pr-number "${{ github.event.pull_request.id }}" --gh-pr-title "${{ github.event.pull_request.title }}"  