name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
  workflow_dispatch:

jobs:
  rust-pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check runner_tools
        uses: actions/checkout@v4
        with:
          repository: StarCitizenToolBox/runner_tools
          path: runner_tools
          ref: dev
        
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "runner_tools/localization"
          cache-all-crates: true

      - name: PR Check
        run: cargo run --release --manifest-path ./runner_tools/localization/Cargo.toml -- -m pr_check --gh-repo ${{ github.repository }} --gh-pr-number ${{ github.event.pull_request.id }} --gh-pr-title ${{ github.event.pull_request.title }}